name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/demo-app:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/demo-app:${{ github.sha }}
    
        - name: Deploy to Azure Container Apps
          run: |
            az containerapp update \
              --name demo-app \
              --resource-group ${{ secrets.RESOURCE_GROUP }} \
              --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/demo-app:${{ github.sha }} \
              --environment ${{ secrets.CONTAINER_APP_ENV }}
              --target-port 8080 \
              --ingress external \
              --registry-server planetscore.azurecr.io \
              --min-replicas 0 \
              --max-replicas 1

